### PR TITLE
update the file command and regex to catch a broader range of text files

### LINKED ISSUE #55: Attempting to edit an xml file produced a warning
I tried to open an xml file for edit and saw this:

>The file you are attempting to edit is not in plain text format.
> application/xml

Reproduced in version v1.2.2 of file editor.

screen shot 2017-03-09 at 1 47 17 pm

### PR DESCRIPTION
**Pull request by brianmcmichael**
Fixes #55.

### CODE REVIEW

**Comment by nickjer** [comment]
Doesn't work for `svg` images:

```sh
┌─[jnicklas@owens-login04][~/ttt]
└─▪ file -b /users/appl/jnicklas/ttt/USStates.svg 
SVG Scalable Vector Graphics image
```

**Comment by nickjer** [comment]
Doesn't work for SSH keys:

```sh
┌─[jnicklas@owens-login04][~/ttt]
└─▪ file -b ~/.ssh/id_rsa.pub
OpenSSH RSA public key
┌─[jnicklas@owens-login04][~/ttt]
└─▪ file -b ~/.ssh/id_rsa
PEM RSA private key

```

**Comment by nickjer** [comment]
Doesn't work for SSL certs:

```sh
┌─[jnicklas@owens-login04][~/ttt]
└─▪ file -b /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
PEM certificate
```

**Comment by nickjer** [comment]
For the last three examples the mime types are `text/plain` and for the SVG image it is `image/svg+xml`.

**Comment by brianmcmichael** [comment]
Maybe the solution is just to expand the original mime type inclusion pattern to catch known editable types, then. It's mostly been working, but there's the problem of the xml file being `application/xml` and now svg files being `image/svg+xml`.

In both cases the app still lets you edit them, it just adds an extra step by way of the warning. I think it's still important to keep the warning though.

**Comment by ericfranz** [comment]
What are the ramifications if we just omit the warning?

**Comment by brianmcmichael** [comment]
High likelihood of accidental data corruption. You probably don't want to be editing binary files as text.

**Comment by nickjer** [comment]
Maybe this can give you some inspiration for a whitelist:

https://www.iana.org/assignments/media-types/media-types.xhtml

Although, most editors let you open up binary files without warnings. It is up to the user to not make changes and save it.

**Comment by brianmcmichael** [comment]
The plot thickens.

I've discovered two `.xml` files in the same application with different `mime-types`, so not all XML files throw this warning.

```
 2017-03-14 11:09:38 ⌚  ruby02 in ~/Qt5.4.0
○ → file -b --mime-type network.xml
application/xml

 2017-03-14 11:09:54 ⌚  ruby02 in ~/Qt5.4.0
○ → file -b --mime-type components.xml
text/plain
```

In any case, it appears that based on Jeremy's investigation that this PR in it's current state is not a comprehensive solution.

**Comment by nickjer** [comment]
It is the header in the `*.xml` file.

**Comment by brianmcmichael** [comment]
Updated to capture SVG

svg

**Pull request merged**
