### PR TITLE
Update ace to package 03.12.16

### PR DESCRIPTION
**Pull request by brianmcmichael**
Solution for https://github.com/OSC/ood-fileeditor/issues/22

* Update to the latest Ace Editor

When pasting a long line to the editor without word wrap, the horizontal scrollbar no longer disappears. The size of the scrollbar is not initially calculated correctly, but it resolves itself once the text or bar is manipulated. This is an improvement over the scrollbar disappearing entirely.

### CODE REVIEW

**Comment by ericfranz** [comment]
These assets are not cache busted so no active users will see these changes. I assigned this to Basil as well who might work on this today. Basically we need to take two more steps:

1. add the un-minified source (still no conflict) under vendor/assets/
2. delete the minifed source files from the public directory that its currently in
3. update (if necessary) the config so the manifest can find assets under vendor
4. include ace in the application.js manifest

**Comment by ericfranz** [comment]
Also https://gist.github.com/benjaminheng/65c82d081fbc994122b1 for some example.

**Comment by nickjer** [comment]
Or if you use bower for latest and greatest code you can see what I do on https://github.com/AweSim-OSC/vftwebapp

**Comment by basilgohar** [comment]
So, after looking at this, the structure of ace prevents it from being compatible by default with the cache-busting of being compiled into the asset pipeline of a Rails app.  This is probably why @brianmcmichael put it all into /public in the first place, as each mode change or theme change makes an explicit call out into a discrete `mode-${mode}`.js or `theme-${theme}`.js under /public.

**Comment by ericfranz** [comment]
FWIW the mode and theme files together make up 4.2M. The rest of the Ace editor js files combined without the mode and theme files make up 2.8M. 

ace.js + keybinding* take up 472K.
the worker-* and ext* files take up 2.3M.

So naively adding everything to the application.js like I suggested adds extra data to transfer on initial load.

**Comment by ericfranz** [comment]
In response to @nickjer 's comment, this is the relevant code https://github.com/AweSim-OSC/vftwebapp/search?utf8=✓&q=bower_components&type=

But bower doesn't fix the problem Basil pointed out.

**Comment by brianmcmichael** [comment]
Ace is also available via CDN at https://cdnjs.com/libraries/ace/

Particularly, we would need to load https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js

I'm not sure if it's smart enough to link up the modes on the same path or if they would need to be called explicitly.

I know we kind of have an internal policy against CDN's but I'm throwing it out there as an option.

**Comment by ericfranz** [comment]
Ha ha ha there it is. The simple option for cache busting. Instead of storing the files in `public/ace-src-min-noconflict/ace.js` we can add the ace version number to this directory:

`public/ace-src-min-noconflict-3.12.16/ace.js`

We can follow the example of cdn cloudflare:

`public/ace/3.12.16/ace.js`

And then update the layout to include the correct javascript at the correct path.

In the future, when updating a version, we would:

1. create a new directory under ace for that version
2. copy the ace files to this directory
3. update the layout to use the new location
4. delete the older ace version that is not used

Cache busting will now work since the URL is new.

**Comment by basilgohar** [comment]
@ericfranz That sounds like a solution to me (the versioned directories approach).

**Comment by ericfranz** [comment]
@brianmcmichael let @basilgohar complete this

**Comment by brianmcmichael** [comment]
Ok. You might still need to update the code to set the base path.

See http://stackoverflow.com/questions/14053820/how-to-set-the-source-path-in-ace-editor/23115903#23115903

**Comment by brianmcmichael** [comment]
This PR superseded by #69

**Pull request closed without merging**
