### PR TITLE
Updated ace package to 03.12.16 with cache busting

### LINKED ISSUE #22: Horizontal scroll bar lost when word wrap turned off
In the File Editor, the horizontal scroll bar can be lost even when word wrap is turned off and the text goes past the page. The only way to recover the scroll bar is to select a character after the frame cut off.
To reproduce: Create a new file, edit it, then type one long continuous word that extends past the frame. Then turn on then off Word Wrap. The horizontal scroll bar will then be gone. This can also be repeated after fixing the horizontal scroll bar.

https://github.com/OSC/ondemand-testing/issues/10#issuecomment-223632290

### PR DESCRIPTION
**Pull request by basilgohar**
Fixes #22

### CODE REVIEW

**Comment by brianmcmichael** [comment]
Looks good to me.

**Comment by basilgohar** [comment]
This pull request resolves #22, by the way.

**Comment by ericfranz** [comment]
Are the contents of the old public/ace-src-min-noconflict identical to the contents of the new  public/ace/03.12.16? If so, I think if you squash your three commits into 1 commit it will look like a `git mv` + an index view update (for the js include to those files).

I could see your three commits as a single commit because its really a file move + update the reference to the file you just moved. The commit description could then be titled something like

>cache bust ace assets
>
>move ace assets to directory with the version in the name, so that the base URL of ace includes the version
>when we add a new version we will create a new subdirectory with the new ace assets, delete the old, and update the reference

But we could just leave it as is. I just noticed that the commit history doesn't mention anything about cache busting though.

**Comment by ericfranz** [comment]
Its up to you because we haven't as a team decided on prioritizing a clean commit history in PRs, just prioritizing small commits over large ones.

**Comment by basilgohar** [comment]
@ericfranz I'm actually fine with squashing it into a less messy commit, that's why I asked.

**Comment by ericfranz** [comment]
I'm going to merge this. We won't worry about a clean history right now, but thats something to prioritize in the future.

**Pull request merged**
