### PR TITLE
Update to use localstorage instead of cookies

### LINKED ISSUE #63: Font size and theme do not persist among sessions
The user-selected font size is supposed to persist across sessions via a cookie, however this does not appear to be working.

My guess is that since different files are accessible at different URL's, the cookie path is changing and it is not being restored upon reload because it's looking for the wrong path.

The more appropriate and stable solution may be to use localstorage instead of cookies for saving this information.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Fixes #63

Simplify persistence by using localstorage instead of cookies.

### CODE REVIEW

**Comment by ericfranz** [comment]
Is there a better name instead of setLocalStorage and getLocalStorage? These are user preferences that we are storing locally.

Maybe `setUserPreference(key, value)` and `getUserPreference(key)`.

**Comment by brianmcmichael** [comment]
I'll make the change to get this pulled in, but calling this `setUserPreference` seems like a an abstraction, while `setLocalStorage` describes exactly what it does. It supersedes `setCookie`, which is another descriptive method name.

Maybe that's fine, then if the implementation is changed again later, the method calls won't need to be updated.

**Comment by ericfranz** [comment]
Yeah I think the abstraction is appropriate. Of course if you wanted to have a method that describes what it does you could do this:

```js
```

**Comment by brianmcmichael** [comment]
These abstractions have been implemented, this can be merged.

**Pull request merged**
